---
title: "Homework4"
author: "Baxter Worthing"
date: "9/19/2018"
output: html_document
---

## question 1
```{r}
x <- 1.1
a <- 2.2
b <- 3.3

#a.
z <- x^a^b
print(z)
#b.
z <- (x^a)^b
print(z)
#c.
z <- 3*x^3 + 2*x^2 +1
print(z)
```
## question 2

```{r}
#a.
x <- seq(from=8, to=1, by=-1)
y <- seq(from=1, to=8, by=1)
c(y,x)

#b. 
x <- seq(from=1, to=5)
rep(x, times =x)

#c.
x <- seq(from=1, to=5)
y <- seq(from=5, to=1, by=-1)
rep(y, times =x)
```
## question 3
```{r}
cords <- runif(n=2, min = 1, max = 10) 
x <- cords[1]
y <- cords[2]
polarcords <- numeric(length = 2)
polarcords[2] <- atan(y/x)
polarcords[1] <- sqrt(x^2+y^2)
```
## question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")
#a.
queue <- c(queue,"serpent")
#b.
queue <- queue[2:5]
#c
queue <- c("donkey",queue)
#d
queue <- queue[1:4]
#e
queue <- queue[-3] 
#f
queue[3] <- "aphid"
queue <- c(queue,"ant")
#g
queue =="aphid"
```
## question 5
```{r}
x <- seq(from= 1, to=100)
answer <- x[x%%2 != 0 & x%%3 != 0 & x%%7 != 0]  
```
## question 6

```
find: \s{2,}
repalce: ,
```

## question 7

```
find: ,\s(\w+\s\w+\s*\w*$)
replace: ' (\1)'
```
## question 8

```
find: (\d{4}[\s\w]*\.mp3)\s
replace: \1\n

and then

find:^(\d{4})([\s\w]*)(\.mp3)
replace:\2_\1\3
```

##question 9
```
find: ^(\w)\w*,(\w*,)[\d\.]*,(\d+)
replace: \1_\2\3

and then

find: ^(\w)\w*,(\w{4})\w+,[\d\.]*,(\d+)
repalce:\1_\2,\3
```


