---
title: "Homework6"
author: "Baxter Worthing"
date: "10/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

 
```{r eval=FALSE}
# convert iris data to long format with a column called trait to indicate sepal and petal width

longIris <- iris %>%
 gather(Sepal.Length:Petal.Width, key = "trait", value = "measure") %>%
 arrange(Species)

longIrisSpecies <- group_by(longIris, Species)
#find average sepal length for each species
summarize(longIrisSpecies[longIrisSpecies$trait=="Sepal.Length",], meanSLen = mean(measure))

#find average sepal width for each species 
summarize(longIrisSpecies[longIrisSpecies$trait=="Sepal.Width",], meanSWid = mean(measure))

#find average petal length for each species
summarize(longIrisSpecies[longIrisSpecies$trait=="Petal.Length",], meanPLen = mean(measure))

#find average petal width for each species
summarize(longIrisSpecies[longIrisSpecies$trait=="Petal.Width",], meanPWid = mean(measure))
```


***

#second part of homework 6

```{r}

#Simulating and Fitting Data Distributions

library(ggplot2) # for graphics
library(MASS) # for maximum likelihood estimation

# quick and dirty, a truncated normal distribution to work on the solution set

#z <- rnorm(n=3000,mean=0.2)
#z <- data.frame(1:3000,z)
# names(z) <- list("ID","myVar")
# z <- z[z$myVar>0,]
# str(z)
# summary(z$myVar)
```

```{r}
#loading in my own data
z <- read.table("~/Desktop/short_seq", header = TRUE, sep = " ", stringsAsFactors = FALSE)

# fixing header to work with chunks below 

names(z)[2] <- "myVar"

```


```{r}
# plot histogram of data
p1 <- ggplot(data=z, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p1)
```

```{r}
#add empirical density curve

p1 <-  p1 +  geom_density(linetype="dotted",size=0.75)
print(p1)
```

```{r}

#Get maximum lkelihood parameters

normPars <- fitdistr(z$myVar,"normal")
print(normPars)
str(normPars)
normPars$estimate["mean"] # note structure of getting a named attribute

```

```{r}
#plot normal probability density
meanML <- normPars$estimate["mean"]
sdML <- normPars$estimate["sd"]

xval <- seq(0,max(z$myVar),len=length(z$myVar))

 stat <- stat_function(aes(x = xval, y = ..y..), fun = dnorm, colour="red", n = length(z$myVar), args = list(mean = meanML, sd = sdML))
 p1 + stat

```

```{r eval= FALSE}
#plot exponenetial probability density

expoPars <- fitdistr(z$myVar,"exponential")
rateML <- expoPars$estimate["rate"]

stat2 <- stat_function(aes(x = xval, y = ..y..), fun = dexp, colour="blue", n = length(z$myVar), args = list(rate=rateML))
 p1 + stat + stat2
 
```

```{r eval= FALSE}

#plot unifrom probability density 

stat3 <- stat_function(aes(x = xval, y = ..y..), fun = dunif, colour="darkgreen", n = length(z$myVar), args = list(min=min(z$myVar), max=max(z$myVar)))
 p1 + stat + stat2 + stat3
 
```

```{r eval=FALSE}

#plot gamma probability density 

gammaPars <- fitdistr(z$myVar,"gamma")
shapeML <- gammaPars$estimate["shape"]
rateML <- gammaPars$estimate["rate"]

stat4 <- stat_function(aes(x = xval, y = ..y..), fun = dgamma, colour="brown", n = length(z$myVar), args = list(shape=shapeML, rate=rateML))
 p1 + stat + stat2 + stat3 + stat4
 
```

```{r eval= FALSE}

#plot beta probaility density 

pSpecial <- ggplot(data=z, aes(x=myVar/(max(myVar + 0.1)), y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) + 
  xlim(c(0,1)) +
  geom_density(size=0.75,linetype="dotted")

betaPars <- fitdistr(x=z$myVar/max(z$myVar + 0.1),start=list(shape1=1,shape2=2),"beta")
shape1ML <- betaPars$estimate["shape1"]
shape2ML <- betaPars$estimate["shape2"]

statSpecial <- stat_function(aes(x = xval, y = ..y..), fun = dbeta, colour="orchid", n = length(z$myVar), args = list(shape1=shape1ML,shape2=shape2ML))
pSpecial + statSpecial

```

```
So, the normal distribution is by far the best fit for my data. 

```
```{r}

#simulating data based off of my data

simData <- rnorm(n=900, mean= normPars$estimate["mean"], sd = normPars$estimate["sd"])

simData <- data.frame(1:900,simData)

names(simData) <- list("ID","myVar")

# making histogram with new data and comparing to my data

p2 <- ggplot(data=simData, aes(x=myVar, y=..density..)) +
  geom_histogram(color="grey60",fill="cornsilk",size=0.2) 
print(p2)

p2 <-  p2 +  geom_density(linetype="dotted",size=0.75)
print(p2)
print(p1)
```
```
I would say that the model does a pretty good job of simulating the data, but the new distribution does look a bit "more normal". This is because the rnorm function purposefully makes a normal distribution while, my data just happened to fit a normal distribution well.
```


