---
title: "Homework10"
author: "Baxter Worthing"
date: "10/31/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Question 1
```{r}

x <- rep(c(0,1,0),100)
z <- 0
for (i in x) {
  if (i == 0)
    z <- z +1
  
  }


```

#Qestion 2

```{r}

x <- rep(c(0,1,0),100)

length(x[x==0])

```

#Question 3
```{r}

makeMat <- function(x=round(runif(1, min = 1, max = 10),0),
                    y=round(runif(1, min = 1, max = 10),0)) {
  
  rNum <- 1:x
  cNum <- 1:y
  mat <- matrix(nrow = x, ncol = y)
  for (i in rNum) {
    mat[i,] <- seq(i,y*i,cNum[i])
  
} 
 return(mat)  
} 

```


#Question 4

```{r}

set.seed(100)
library(ggplot2)
# load data
readData <- function(z=NULL) {
  if (is.null(z)) {
    xObs <- round(runif(100, min= 400, max= 1200),0) # changed this to simulate transcript sequence length
    error <- runif(100, min = .7, max = 1.3) #added this to make variable error 
    yObs <- round(((xObs + 100) * error),0) # simulating read count that is related to seq length
  
    dFrame <- data.frame(ID=seq_along(xObs), 
                         xObs,
                         yObs)}else{
  
   dF <- read.table(z, header = TRUE, stringsAsFactors = FALSE) # had to change this to match how my data is saved 
   
  return(dF)
    }
  }

# perform linear reagression between Length and Count 

getMetric <- function(z=NULL) {
 . <- lm(z[,3]~z[,2])  
    . <- summary(.) 
    . <- .$coefficients[2,1]  
    slope <- .
    return(slope)
}


# now randomize 
shuffleData <- function(z=NULL) {
z[,3] <- sample(z[,3])

return(z)
}

# get p value

getPVAL <- function(z=NULL) {
pLower <- mean(z[[2]] <= z[[1]]) 
   pUpper <- mean(z[[2]] >= z[[1]])
   return(c(pLower,pUpper))
 }
 

 # make the plot
plotRanTest <- function(z=NULL) {
 dF <- data.frame(ID=seq_along(z[[2]]),simX=z[[2]])
   p1 <- ggplot(data=dF,mapping=aes(x=simX))
   p1 + geom_histogram(mapping=aes(fill=I("goldenrod"),color=I("black"))) +
     geom_vline(aes(xintercept=z[[1]],col="blue")) 
  
 }


# perform test

 nSim <- 1000
 Xsim <- rep(NA, nSim)
dF <- readData() 
Xobs <- getMetric(dF)

for (i in seq_len(nSim)) {
  Xsim[i] <- getMetric(shuffleData(dF))
}

slopes <- list(Xobs,Xsim)
getPVAL(slopes) 

plotRanTest(slopes)

```

#Question 5

```{r, eval= FALSE}
#load real data
SeqLens <- read.table(sequenceLenCount.tab, header = TRUE, stringsAsFactors = FALSE)


 #linear regression with real data
linreg <- lm(SeqLens[,3]~SeqLens[,2])  
    linregSumm <- summary(linreg) 
    pval <- linregSumm$coefficients[2,4]  
    pval
    
#my p-vlaue is tiny (<2e-16), which is in line with the estimated p value from the randomization test    
```